# Dependencies
markdown:         redcarpet
highlighter:      rouge

redcarpet:
  extensions:     ['footnotes', 'smart']

# Permalinks
permalink:        pretty

# Setup
title:            'John Gozde'
tagline:          'Coding in the cold'
description:      'In which I write about software and rant about the weather. It''s cold up here.'
url:              http://jgoz.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'John Gozde'
  url:            https://github.com/jgoz
  twitter:        jmgozde
  github:         jgoz
